export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const START_USER_LOADING = 'START_USER_LOADING';

export const STOP_USER_LOADING = 'STOP_USER_LOADING';

export const USER_FAILURE = 'USER_FAILURE';

export const USER_SUCCESS = 'USER_SUCCESS';

export const LOADED_USER_FALSE = 'LOADED_USER_FALSE';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const STATUS_BAR = 'STATUS_BAR';
