export default {
  modal: false,
  isLoading: false,
  loaded: false,
  success: false,
  user: {
    statusBar: true,
    firstName: '',
    lastName: '',
    email: '',
    telephone: '',
    gender: '',
    password: '',
    newPassword: '',
    confirmPassword: '',
    emailVerified: false,
    address: {
      postalCode: '',
      city: '',
      street: '',
      country: '',
      houseNumber: '',
      doorNumber: '',
      doorBellNumber: '',
    },
    bankAccount: {
      bankName: '',
      accountName: '',
      accountNumber: 0,
    },
    dob: new Date(),
    picture: '',
    savedTrips: [],
    savedItems: [],
  },
};
