export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';

export const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS';

export const GET_MY_APPOINTMENTS_SUCCESS = 'GET_MY_APPOINTMENTS_SUCCESS';

export const GET_APPOINTMENT_SUCCESS = 'GET_APPOINTMENT_SUCCESS';

export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENT_SUCCESS';

export const START_APPOINTMENT_LOADING = 'START_APPOINTMENT_LOADING';

export const STOP_APPOINTMENT_LOADING = 'STOP_APPOINTMENT_LOADING';
