export default {
  isLoading: false,
  loaded: false,
  success: false,
  offset: 0,
  myItems: [],
  myActiveItems: [],
  items: [],
  searchItems: [],
  item: {
    item: {
      name: '',
      description: '',
      initCountry: '',
      initCity: '',
      destCountry: '',
      destCity: '',
      location: { longitude: 0, latitude: 0 },
      price: 0,
      initDate: '',
      category: [],
      images: [],
      image: '',
      appointment: {},
      size: 0,
      savedBy: [],
      user: {
        avatar: '',
        items: [],
        _id: 0,
        ratings: {
          client: 0,
          clientCount: 0,
        },
      },
    },
    conversations: [],
    couriers: [],
    itemOrder: {},
  },
};
