export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
// export const CREATE_ITEM_FAIL = 'CREATE_ITEM_FAIL';

export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCESS';
export const FILTER_ITEMS_SUCCESS = 'FILTER_ITEMS_SUCCESS';
export const CLEAR_SEARCH_ITEMS_SUCCESS = 'CLEAR_SEARCH_ITEMS_SUCCESS';
export const GET_MY_ITEMS_SUCCESS = 'GET_MY_ITEMS_SUCCESS';

export const GET_MY_ACTIVE_ITEMS_SUCCESS = 'GET_MY_ACTIVE_ITEMS_SUCCESS';

export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const UPDATE_ITEM_ATTR_SUCCESS = 'UPDATE_ITEM_ATTR_SUCCESS';

export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';

export const START_ITEM_LOADING = 'START_ITEM_LOADING';

export const STOP_ITEM_LOADING = 'STOP_ITEM_LOADING';

export const ITEM_FAILURE = 'ITEM_FAILURE';

export const ITEM_SUCCESS = 'ITEM_SUCCESS';

export const LOADED_ITEM_FALSE = 'LOADED_ITEM_FALSE';

export const NO_ITEM_DATA = 'NO_ITEM_DATA';

export const SAVE_ITEM_SUCCESS = 'SAVE_ITEM_SUCCESS';

export const DELETE_SAVED_ITEM_SUCCESS = 'DELETE_SAVED_ITEM_SUCCESS';
