export const CREATE_STORE_SUCCESS = 'CREATE_STORE_SUCCESS';

export const UPDATE_STORE_SUCCESS = 'UPDATE_STORE_SUCCESS';

export const GET_STORES_SUCCESS = 'GET_STORES_SUCCESS';

export const LATEST_STORES_SUCCESS = 'LATEST_STORES_SUCCESS';

export const SEARCH_STORES_SUCCESS = 'SEARCH_STORES_SUCCESS';

export const FILTER_STORES_SUCCESS = 'FILTER_STORES_SUCCESS';

export const GET_MY_STORES_SUCCESS = 'GET_MY_STORES_SUCCESS';

export const GET_MY_ACTIVE_STORES_SUCCESS = 'GET_MY_ACTIVE_STORES_SUCCESS';

export const GET_STORE_SUCCESS = 'GET_STORE_SUCCESS';

export const DELETE_STORE_SUCCESS = 'DELETE_STORE_SUCCESS';

export const START_STORE_LOADING = 'START_STORE_LOADING';

export const STOP_STORE_LOADING = 'STOP_STORE_LOADING';

export const INCREASE_OFFSET = 'INCREASE_OFFSET';

export const SAVE_OFFSET = 'SAVE_OFFSET';

export const RESET_OFFSET = 'RESET_OFFSET';

export const START_STORE_REFRESHING = 'START_STORE_REFRESHING';

export const NO_STORE_DATA = 'NO_STORE_DATA';

export const SAVE_STORE_SUCCESS = 'SAVE_STORE_SUCCESS';

export const DELETE_SAVED_STORE_SUCCESS = 'DELETE_SAVED_STORE_SUCCESS';

export const CLEAR_SEARCH_STORES_SUCCESS = 'CLEAR_SEARCH_STORES_SUCCESS';
