export const CREATE_ITEM_ORDER_SUCCESS = 'CREATE_ITEM_ORDER_SUCCESS';

export const GET_ITEM_ORDERS_SUCCESS = 'GET_ITEM_ORDERS_SUCCESS';

export const GET_MY_ITEM_ORDERS_SUCCESS = 'GET_MY_ITEM_ORDERS_SUCCESS';

export const GET_ITEM_ORDER_SUCCESS = 'GET_ITEM_ORDER_SUCCESS';

export const DELETE_ITEM_ORDER_SUCCESS = 'DELETE_ITEM_ORDER_SUCCESS';

export const START_ITEM_ORDER_LOADING = 'START_ITEM_ORDER_LOADING';

export const STOP_ITEM_ORDER_LOADING = 'STOP_ITEM_ORDER_LOADING';
