export const SET_ASYNC_STORAGE_SUCCESS = 'SET_ASYNC_STORAGE_SUCCESS';
export const SAVE_FILTER_SUCCESS = 'SAVE_FILTER_SUCCESS';
export const SAVE_DATE_TIME_SUCCESS = 'SAVE_DATE_TIME_SUCCESS';
export const SAVE_ITEM_TRIP_SUCCESS = 'SAVE_ITEM_TRIP_SUCCESS';
export const SAVE_MODE_MAIL_SUCCESS = 'SAVE_MODE_MAIL_SUCCESS';
export const SAVE_ADDRESS_SUCCESS = 'SAVE_ADDRESS_SUCCESS';
export const RESET_STATE = 'RESET_STATE';
export const COUNTRY_PICKER = 'COUNTRY_PICKER';
export const STATE_REGION_PICKER = 'STATE_REGION_PICKER';

export const TOGGLE_LOADER = 'TOGGLE_LOADER';
