export const CREATE_TRIP_SUCCESS = 'CREATE_TRIP_SUCCESS';

export const UPDATE_TRIP_SUCCESS = 'UPDATE_TRIP_SUCCESS';

export const GET_TRIPS_SUCCESS = 'GET_TRIPS_SUCCESS';

export const LATEST_TRIPS_SUCCESS = 'LATEST_TRIPS_SUCCESS';

export const SEARCH_TRIPS_SUCCESS = 'SEARCH_TRIPS_SUCCESS';

export const FILTER_TRIPS_SUCCESS = 'FILTER_TRIPS_SUCCESS';

export const GET_MY_TRIPS_SUCCESS = 'GET_MY_TRIPS_SUCCESS';

export const GET_MY_ACTIVE_TRIPS_SUCCESS = 'GET_MY_ACTIVE_TRIPS_SUCCESS';

export const GET_TRIP_SUCCESS = 'GET_TRIP_SUCCESS';

export const DELETE_TRIP_SUCCESS = 'DELETE_TRIP_SUCCESS';

export const START_TRIP_LOADING = 'START_TRIP_LOADING';

export const STOP_TRIP_LOADING = 'STOP_TRIP_LOADING';

export const INCREASE_OFFSET = 'INCREASE_OFFSET';

export const SAVE_OFFSET = 'SAVE_OFFSET';

export const RESET_OFFSET = 'RESET_OFFSET';

export const START_TRIP_REFRESHING = 'START_TRIP_REFRESHING';

export const NO_TRIP_DATA = 'NO_TRIP_DATA';

export const SAVE_TRIP_SUCCESS = 'SAVE_TRIP_SUCCESS';

export const DELETE_SAVED_TRIP_SUCCESS = 'DELETE_SAVED_TRIP_SUCCESS';

export const CLEAR_SEARCH_TRIPS_SUCCESS = 'CLEAR_SEARCH_TRIPS_SUCCESS';
